import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: "Idea Hub | Amrit ",
    template: "%s | Idea Hub"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className='container max-w-6xl m-auto min-h-screen flex flex-col justify-between px-[50px]'>
          <div className='mb-[80px]'>
            <Navbar />
          </div>

          <div className='px-2 '>
            {children}
          </div>

          <div className='mt-[100px]'>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
